version: "3"

services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - shard_db:/data/db
    ports:
      - "27017:27017"

  backup_mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - shard_db:/data/db

  volumes:
    shard_db;    

  api-server:
    build:
      context: .
    container_name: api-server
    image: api-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://host.docker.internal:27017/dsh
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge
